name: 压缩资源包(push)

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 刷新软件源
      run: sudo apt update

    - name: 安装工具依赖
      run: sudo apt-get install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad

    - name: 构建
      run: ./makepackage.sh
    
    - name: 上传构建结果
      uses: actions/upload-artifact@v3
      with:
        path: |
          build/*.zip
          build/*-sha1